task:
    # Basic metadata:
    name: Gradle Build
    trigger_type: manual

    # The build machine:
    container:
        image: openjdk:17.0.2-oracle

    # No environment variables provided.

    # Instructions:
    Build_Gradle_Project_script: ./gradlew && ./gradlew jar
    Grasscutter_artifacts:
        path: grasscutter-*.jar
