task:
    # Basic metadata:
    name: Gradle Build
    only_if : true

    # The build machine:
    osx_instance:
        image: big-sur-base

    # No environment variables provided.

    # Instructions:
    Build_Gradle_Project_script: ./gradlew && ./gradlew jar
    Grasscutter_artifacts:
        path: grasscutter-*.jar
