pipelines:
  build:
    image: 17.0.3_7-jdk-jammy
    commands:
    - ./gradlew && ./gradlew jar
  upload:
    image: woodpeckerci/plugin-s3
    bucket: gc-artifacts
    access_key: jvllxxys2kodniqyjfsrofwvrbeq
    secret_key: j3nbqguaffbnkkbv6xsewyepsletkr3p2mc7uottkoepdtwb4iqmk
    source: grasscutter-*.jar
    endpoint: https://gateway.storjshare.io
