name: "Build"
on:
  workflow_dispatch: ~
  push:
    paths:
      - "**.java"
    branches:
      - "Patch-DEV"
      - "Patch"
      - "Patch-2.7"
    
jobs:
  Build-Server-Jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Run Gradle
        run: ./gradlew && ./gradlew jar
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_ENDPOINT: https://gateway.storjshare.io
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: '/home/runner/work/Grasscutter/Grasscutter/grasscutter-*.jar'
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Grasscutter
          path: grasscutter-*.jar
